---
#
# Ansible managed
#
repository:
  description: Install and configure unowned_files on your system.
  homepage: https://buluma.github.io/
  topics: unownedfiles, ansible, molecule, tox, playbook
